# Docker профиль - через переменные окружения
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/document_db
    username: document_user
    password: document_password

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.itq.document: INFO
    org.hibernate.SQL: DEBUG