# Docker профиль - через переменные окружения
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  
  jpa:
    show-sql: false

app:
  worker:
    submit:
      fixed-delay: ${SUBMIT_WORKER_DELAY:60000}
      batch-size: ${SUBMIT_BATCH_SIZE:100}
    approve:
      fixed-delay: ${APPROVE_WORKER_DELAY:60000}
      batch-size: ${APPROVE_BATCH_SIZE:100}

logging:
  level:
    com.itq.document: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"